#!/usr/bin/env bash

#
# find all eyd files
# convert to tsv if needed
#

echo "[20190625] WARNING: RPGPet eyd parsed here are not used; instead '*_fake.tsv' generated by /Volumes/Phillips/mMR_PETDA/scripts/fake_eyd.m" >&2
tsvListFile="tsvs.ls"
echo -n > $tsvListFile
for f in $(
         find /mnt/B/bea_res/Data/Tasks/RPG/mMR/ -maxdepth 3 -mindepth 3 -iname '*_run[1-6].eyd' -newermt 2013-03-01| 
          sort -t/ -k10nr # do newest first
         ); do

 echo $f
 outdir="$(dirname "$f")/txt"
 [ ! -d $outdir ] && mkdir -p $outdir

 fname=$(echo $f | perl -lne 'print "$+{id}.$+{date}.rpg.$+{run}.tsv" if m:/(?<id>\d{5})/(?<date>\d{8}).*run(?<run>[1-6]):')
 [ -z "$fname" ] && echo "ISSUE: bad name $f"  && continue
 tsv="$outdir/$fname"
 echo "$tsv" >> $tsvListFile

 [ -r $tsv -a -s $tsv ] && echo "skipping $tsv" && continue

 #echo "   $tsv"
 ../dataFromAnyEyd.pl $f > $tsv
done
