#### Settings ######

# XDAT CODES
# 20190625 - generated by /Volumes/Phillips/mMR_PETDA/scripts/fake_eyd.m
startcodes   <- 1
targetcodes  <- c(21,22,41,42)
stopcodes    <- 250

# if we cared about it, getExpPos would get startcode appended to targetcode (like 121 instead of 21)
CAREABOUTSTARTCODE <- FALSE

# number of trials
expectedTrialLengths  <- 8

#minium distance to be considered a saccade
sac.minmag   <-  10      # min abs of x position change -- set very low, inc to 20 at LR request :)

## xpos ##
# saccade left thresholds
sac.left.small  <- 100

# saccade right thresholds
sac.right.small <- 160

# acceleration -- needs to be this many pixels per sample before considering saccade
lat.minvel   <- 5      # ASLcoordx/60Hz 
# 20190625, with default of 4, dropping 3178 b/c moving

# if there are spikes in fixation, bad tracking, drop
# 99 means don't worry about it
maxSamplesFromBaseline <- 99

# padding to give to expected positions
sac.padding     <- 30

# the useful saccades probably already occur
sac.majorRegionEnd <- .75 
  
sac.thresholds <- c( sac.right.small, sac.left.small )


## FUNCTIONS
# where are the files?
filebasedir <- '/mnt/B/bea_res/Data/Tasks/RPG/mMR/'
getFiles <- function(filesFrom=sprintf('%s/*/*/txt/*.fake.tsv',filebasedir)) {
 #/mnt/B/bea_res/Data/Tasks/RPG/mMR/11520/20140414/txt/11520.20140414.rpg.6.tsv
 files     <- Sys.glob(filesFrom)
 splitfile <- strsplit(basename(files),'\\.')
 splitfile <- as.data.frame(t(sapply(splitfile,rbind)))[,-5]
 names(splitfile)  <- c('subj','date','run')
 splitfile$subj    <- as.character(splitfile$subj)
 splitfile$date    <- as.character(splitfile$date)
 splitfile$type    <- 'Anti'
 #should always be 1?
 splitfile$run     <- as.numeric(as.character(splitfile$run))
 splitfile$file    <- files
 splitfile$id      <- paste(splitfile$subj, splitfile$date,splitfile$run, sep=".")  
 splitfile$savedas <- paste(filebasedir,splitfile$subj,'/',splitfile$date, '/txt/fake_scored/',
                            paste(splitfile$subj,splitfile$date,splitfile$run,'sac.txt',sep="."),
                            sep="" )
 return(splitfile)
}
# what is the threshold for left/right position
getExpPos <- function(sac.thresholds, xdatCode){
    # xdatCode is index for thesholds (21,22 is right, 41,42 is left)
    idx <- floor(xdatCode/10)/2 # 21 -> 2 -> 1; 42 -> 4 -> 2
    return(sac.thresholds[idx] )
}

# is this xdat an antisaccde xdat?
xdatIsAS <- function(xdat){
 return(TRUE)
}
trialIsType <- function(xdat){
 return('AS')
}
